# Generated by Django 4.2.29 on 2026-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('PARTNER', 'Partner'), ('OWN', 'Own')], default='PARTNER', max_length=16, verbose_name='type')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('supports_pickup', models.BooleanField(default=True, verbose_name='supports pickup')),
                ('supports_delivery', models.BooleanField(default=True, verbose_name='supports delivery')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Production Center',
                'verbose_name_plural': 'Production Centers',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
