# Generated by Django 5.2.11 on 2026-02-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialconnection',
            name='unique_provider_connection',
        ),
        migrations.RenameIndex(
            model_name='socialconnection',
            new_name='users_socia_user_id_0647d4_idx',
            old_name='users_social_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='socialconnection',
            new_name='users_socia_provide_d9ae01_idx',
            old_name='users_social_provider_idx',
        ),
        migrations.AlterUniqueTogether(
            name='socialconnection',
            unique_together={('provider', 'provider_id')},
        ),
    ]
