# Generated by Django 4.2.29 on 2026-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_orders',
            field=models.BooleanField(default=False, verbose_name='can manage orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_pickup_locations',
            field=models.BooleanField(default=False, verbose_name='can manage pickup locations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_products',
            field=models.BooleanField(default=False, verbose_name='can manage products'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('print_operator', 'Print Operator'), ('manager', 'Manager'), ('admin', 'Admin'), ('support', 'Support')], default='customer', max_length=20, verbose_name='role'),
        ),
    ]
