# Generated by Django 4.2.29 on 2026-07-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('users', '0004_user_can_manage_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_manage_orders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_pickup_locations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_products',
        ),
        migrations.AddField(
            model_name='user',
            name='production_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='production.productioncenter', verbose_name='production center'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('production_manager', 'Production Manager'), ('production_admin', 'Production Admin'), ('super_admin', 'Super Admin'), ('support', 'Support')], default='customer', max_length=20, verbose_name='role'),
        ),
    ]
