# Generated by Django 4.2.29 on 2026-03-26 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_productvariant_unique_product_variant_and_more'),
        ('designs', '0003_alter_draft_editor_state_alter_draft_text_layers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('READY_FOR_PRODUCTION', 'Ready for Production'), ('IN_PRODUCTION', 'In Production'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=32, verbose_name='status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='shipping cost')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='shipping name')),
                ('shipping_email', models.EmailField(max_length=254, verbose_name='shipping email')),
                ('shipping_phone', models.CharField(blank=True, max_length=20, verbose_name='shipping phone')),
                ('shipping_address', models.TextField(verbose_name='shipping address')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='shipping city')),
                ('shipping_state', models.CharField(max_length=100, verbose_name='shipping state')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='shipping postal code')),
                ('shipping_country', models.CharField(default='Uzbekistan', max_length=100, verbose_name='shipping country')),
                ('customer_notes', models.TextField(blank=True, verbose_name='customer notes')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='tracking number')),
                ('carrier', models.CharField(blank=True, max_length=50, verbose_name='carrier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='coupon code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('product_type', models.CharField(max_length=50, verbose_name='product type')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='product SKU')),
                ('size', models.CharField(max_length=20, verbose_name='size')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('design_title', models.CharField(blank=True, max_length=200, verbose_name='design title')),
                ('design_file_url', models.URLField(blank=True, verbose_name='design file URL')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('print_specifications', models.JSONField(default=dict, help_text='Print specifications and positioning', verbose_name='print specifications')),
                ('production_status', models.CharField(choices=[('pending', 'Pending'), ('designing', 'Designing'), ('ready', 'Ready for Print'), ('printing', 'Printing'), ('quality_check', 'Quality Check'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='production status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='designs.design')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base cost')),
                ('cost_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost per item')),
                ('min_delivery_days', models.PositiveIntegerField(verbose_name='min delivery days')),
                ('max_delivery_days', models.PositiveIntegerField(verbose_name='max delivery days')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('available_countries', models.JSONField(default=list, verbose_name='available countries')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['base_cost'],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Assignment',
                'verbose_name_plural': 'Order Assignments',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shippingmethod'),
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_internal_notes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='orders.order')),
            ],
            options={
                'verbose_name': 'Internal Note',
                'verbose_name_plural': 'Internal Notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='coupon code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount value')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage limit')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='usage count')),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='per user limit')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_to', models.DateTimeField(verbose_name='valid to')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='minimum amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('png_300', 'PNG 300 DPI'), ('pdf', 'PDF'), ('other', 'Other')], default='png_300', max_length=32, verbose_name='file type')),
                ('s3_key', models.CharField(max_length=500, verbose_name='S3 key')),
                ('dpi', models.PositiveIntegerField(default=300, verbose_name='DPI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_files', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_files', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Production File',
                'verbose_name_plural': 'Production Files',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'order_item'], name='orders_prod_order_i_b9ecff_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzcard_humo', 'Uzcard/Humo Direct')], max_length=32, verbose_name='provider')),
                ('amount_uzs', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='amount (UZS)')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=16, verbose_name='status')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='external transaction id')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='idempotency key')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'external_id'], name='orders_paym_provide_50bc10_idx'), models.Index(fields=['order', 'status'], name='orders_paym_order_i_d9ec6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='payment ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='gateway transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='gateway response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_paym_order_i_e3de73_idx'), models.Index(fields=['payment_method', 'status'], name='orders_paym_payment_753274_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'production_status'], name='orders_orde_order_i_b77ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['operator'], name='orders_orde_operato_03a64b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
    ]
