# Generated by Django 4.2.29 on 2026-07-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('orders', '0004_pickuplocation_order_pickup_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderassignment',
            name='orders_orde_operato_03a64b_idx',
        ),
        migrations.RenameField(
            model_name='orderassignment',
            old_name='operator',
            new_name='manager',
        ),
        migrations.AddField(
            model_name='order',
            name='production_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.productioncenter'),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='production_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='production.productioncenter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('READY_FOR_PRODUCTION', 'Ready for Production'), ('IN_PRODUCTION', 'In Production'), ('QUALITY_CHECK', 'Quality Check'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=32, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['manager'], name='orders_orde_manager_b3b765_idx'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['production_center'], name='orders_orde_product_be19b3_idx'),
        ),
    ]
