# Generated by Django 5.2.11 on 2026-02-24 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
        ('products', '0003_remove_productvariant_unique_product_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for this render job', unique=True, verbose_name='render ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('task_id', models.CharField(blank=True, help_text='ID of the Celery task handling this render', max_length=255, null=True, verbose_name='Celery task ID')),
                ('output_image_s3_key', models.CharField(blank=True, help_text='S3 key for the rendered preview image', max_length=500, null=True, verbose_name='output image S3 key')),
                ('output_thumbnail_s3_key', models.CharField(blank=True, help_text='S3 key for the rendered thumbnail', max_length=500, null=True, verbose_name='output thumbnail S3 key')),
                ('error_message', models.TextField(blank=True, help_text='Error details if rendering failed', null=True, verbose_name='error message')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times this render has been retried', verbose_name='retry count')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='processing started at')),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='processing completed at')),
                ('output_width', models.PositiveIntegerField(blank=True, help_text='Width of the rendered image in pixels', null=True, verbose_name='output width')),
                ('output_height', models.PositiveIntegerField(blank=True, help_text='Height of the rendered image in pixels', null=True, verbose_name='output height')),
                ('output_file_size', models.PositiveIntegerField(blank=True, help_text='Size of the rendered image in bytes', null=True, verbose_name='output file size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Mockup Render',
                'verbose_name_plural': 'Mockup Renders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMockupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Front View", "Back View", "Flat Lay"', max_length=100, verbose_name='template name')),
                ('template_s3_key', models.CharField(help_text='S3 key for the base mockup template', max_length=500, verbose_name='template S3 key')),
                ('design_area_x', models.PositiveIntegerField(default=0, verbose_name='design area X')),
                ('design_area_y', models.PositiveIntegerField(default=0, verbose_name='design area Y')),
                ('design_area_width', models.PositiveIntegerField(verbose_name='design area width')),
                ('design_area_height', models.PositiveIntegerField(verbose_name='design area height')),
                ('template_width', models.PositiveIntegerField(verbose_name='template width')),
                ('template_height', models.PositiveIntegerField(verbose_name='template height')),
                ('design_rotation', models.FloatField(default=0.0, help_text='Rotation angle in degrees for the design on this template', verbose_name='design rotation')),
                ('design_opacity', models.FloatField(default=1.0, help_text='Opacity for the design overlay (0.0 to 1.0)', verbose_name='design opacity')),
                ('perspective_matrix', models.JSONField(blank=True, help_text='8-value transformation matrix for perspective correction', null=True, verbose_name='perspective transformation matrix')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Product Mockup Template',
                'verbose_name_plural': 'Product Mockup Templates',
                'ordering': ['product_type', 'sort_order', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='designcollection',
            name='unique_collection_per_user',
        ),
        migrations.RenameIndex(
            model_name='draft',
            new_name='designs_dra_custome_1ac696_idx',
            old_name='designs_draft_customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='draft',
            new_name='designs_dra_uuid_b9788b_idx',
            old_name='designs_draft_uuid_idx',
        ),
        migrations.RenameIndex(
            model_name='draft',
            new_name='designs_dra_product_b8009f_idx',
            old_name='designs_draft_product_idx',
        ),
        migrations.RenameIndex(
            model_name='draftasset',
            new_name='designs_dra_draft_i_7412b7_idx',
            old_name='designs_draftasset_draft_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='draftasset',
            new_name='designs_dra_uuid_ff5657_idx',
            old_name='designs_draftasset_uuid_idx',
        ),
        migrations.RenameIndex(
            model_name='draftasset',
            new_name='designs_dra_s3_key_c7a66b_idx',
            old_name='designs_draftasset_s3_key_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadsession',
            new_name='designs_upl_session_71f870_idx',
            old_name='designs_uploadsession_session_id_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadsession',
            new_name='designs_upl_user_id_b6a43c_idx',
            old_name='designs_uploadsession_user_confirmed_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadsession',
            new_name='designs_upl_s3_key_f3f518_idx',
            old_name='designs_uploadsession_s3_key_idx',
        ),
        migrations.AlterUniqueTogether(
            name='designcollection',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='mockuprender',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_renders', to='designs.draft'),
        ),
        migrations.AddField(
            model_name='mockuprender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_renders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmockuptemplate',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_templates', to='products.producttype'),
        ),
        migrations.AddField(
            model_name='productmockuptemplate',
            name='product_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant, if null applies to all variants of the product type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mockup_templates', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='mockuprender',
            name='mockup_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='designs.productmockuptemplate'),
        ),
        migrations.AddIndex(
            model_name='productmockuptemplate',
            index=models.Index(fields=['product_type', 'is_active'], name='designs_pro_product_202bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='productmockuptemplate',
            index=models.Index(fields=['product_variant', 'is_active'], name='designs_pro_product_60f81b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productmockuptemplate',
            unique_together={('product_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='mockuprender',
            index=models.Index(fields=['render_id'], name='designs_moc_render__5474ae_idx'),
        ),
        migrations.AddIndex(
            model_name='mockuprender',
            index=models.Index(fields=['draft', 'status'], name='designs_moc_draft_i_c0d522_idx'),
        ),
        migrations.AddIndex(
            model_name='mockuprender',
            index=models.Index(fields=['user', 'status'], name='designs_moc_user_id_3755d8_idx'),
        ),
        migrations.AddIndex(
            model_name='mockuprender',
            index=models.Index(fields=['status', 'created_at'], name='designs_moc_status_0805bd_idx'),
        ),
        migrations.AddIndex(
            model_name='mockuprender',
            index=models.Index(fields=['task_id'], name='designs_moc_task_id_9bafe5_idx'),
        ),
    ]
