# Generated by Django 4.2.29 on 2026-03-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0002_mockuprender_productmockuptemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="editor_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete editor state including transforms, positions, layers order",
                verbose_name="editor state",
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="text_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Text elements with positioning, styling, and content",
                verbose_name="text layers",
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["created_by", "status"], name="designs_des_created_c0e05e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["status", "is_public"], name="designs_des_status_9c2051_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["category", "status"], name="designs_des_categor_9e35e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["-created_at"], name="designs_des_created_e3335c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["design_type", "status"], name="designs_des_design__c790bb_idx"
            ),
        ),
    ]
