# Generated by Django 5.2.11 on 2026-02-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_populate_mvp_catalog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_variant',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product_type', 'size', 'color')},
        ),
    ]
