# Generated by Django 4.2.30 on 2026-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20260416_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='category',
            field=models.CharField(choices=[('tshirt', 'T-Shirt'), ('mug', 'Mug'), ('business_card', 'Business Card'), ('desk_calendar', 'Desk Calendar'), ('pen', 'Pen')], max_length=20, unique=True, verbose_name='category'),
        ),
    ]
